-- =====================================================
-- Problem: Top 2 Highest-Grossing Products
-- Platform: DataLemur
-- Difficulty: Medium
-- =====================================================

/*
Problem Statement

Amazon wants to identify the top two
highest-grossing products within each
product category for the year 2022.

Calculate the total spend for each
product and return:

- category
- product
- total_spend

Only include the top 2 products
(by total spend) within each category.
*/

-- =====================================================
-- Table Schema
-- =====================================================

/*
product_spend

+------------------+-----------+
| Column Name      | Type      |
+------------------+-----------+
| category         | string    |
| product          | string    |
| user_id          | integer   |
| spend            | decimal   |
| transaction_date | timestamp |
+------------------+-----------+
*/

-- =====================================================
-- Solution
-- =====================================================

WITH product_totals AS (
    SELECT
        category,
        product,
        SUM(spend) AS total_spend
    FROM product_spend
    WHERE EXTRACT(YEAR FROM transaction_date) = 2022
    GROUP BY
        category,
        product
),

ranked_products AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY total_spend DESC
        ) AS rn
    FROM product_totals
)

SELECT
    category,
    product,
    total_spend
FROM ranked_products
WHERE rn <= 2;

-- =====================================================
-- Explanation
-- =====================================================

/*
1. Filter 2022 Transactions

   Keep only purchases made during
   the year 2022.

2. Calculate Total Spend

   Group by:

   - category
   - product

   SUM(spend) computes the total
   revenue generated by each product.

3. Rank Products

   ROW_NUMBER() assigns a ranking
   within each category based on
   total spend in descending order.

4. Return Top 2 Products

   Keep only rows where rn <= 2,
   which gives the two highest-
   grossing products in each category.
*/

-- =====================================================
-- Time Complexity
-- =====================================================

/*
O(n log n)

n = number of rows in product_spend

- GROUP BY aggregates all transactions.
- ROW_NUMBER() sorts products within
  each category.
- Final filtering is O(n).
*/

-- =====================================================
-- Key Concepts
-- =====================================================

/*
- Common Table Expression (CTE)
- GROUP BY
- SUM()
- Window Functions
- ROW_NUMBER()
- PARTITION BY
- ORDER BY
- EXTRACT()
*/
